# Generated by Django 4.1.7 on 2023-05-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='DownVote',
        ),
        migrations.DeleteModel(
            name='UpVote',
        ),
    ]
